-- MySQL Script generated by MySQL Workbench
-- 10/18/16 17:23:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema urbanAgriDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `urbanAgriDB` ;

-- -----------------------------------------------------
-- Schema urbanAgriDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urbanAgriDB` DEFAULT CHARACTER SET utf8 ;
USE `urbanAgriDB` ;

-- -----------------------------------------------------
-- 1 Table `urbanAgriDB`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Company` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Company` (
  `id` INT NOT NULL,
  `name` VARCHAR(1000) NULL DEFAULT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- 2 Table `urbanAgriDB`.`OnGroundInstallation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`OnGroundInstallation` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`OnGroundInstallation` (
  `id` INT NOT NULL,
  `country` VARCHAR(500) NULL DEFAULT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `zipCode` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 3 Table `urbanAgriDB`.`OnRoofInstallation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`OnRoofInstallation` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`OnRoofInstallation` (
  `id` INT NOT NULL,
  `country` VARCHAR(500) NULL DEFAULT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `zipCode` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 4 Table `urbanAgriDB`.`Objective`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Objective` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Objective` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 5 Table `urbanAgriDB`.`Business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Business` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Business` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 6 Table `urbanAgriDB`.`IrrigationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`IrrigationType` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`IrrigationType` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 7 Table `urbanAgriDB`.`InstallationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`InstallationType` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`InstallationType` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 8 Table `urbanAgriDB`.`FertilisationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FertilisationType` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FertilisationType` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 9 Table `urbanAgriDB`.`PhytosanitaryFightType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`PhytosanitaryFightType` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`PhytosanitaryFightType` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 10 Table `urbanAgriDB`.`FruitsAndVegetablesProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 11 Table `urbanAgriDB`.`FarmingProducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FarmingProducts` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FarmingProducts` (
  `id` INT NOT NULL,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- 12 Table `urbanAgriDB`.`CommercializationMode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`CommercializationMode` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`CommercializationMode` (
  `id` INT NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `name` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- LINKS TABLES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- 13 Table `urbanAgriDB`.`CompanyLocation_OnGroundInstallation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (
  `idCompany` INT NOT NULL,
  `idInstallation` INT NOT NULL,
  `responsibleName` VARCHAR(500) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  `employeesNumber` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `responsibleFirstName` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`, `idInstallation`),
  CONSTRAINT `idCompanyConstraint_CompanyLocation_OnGroundInstallation`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`Company` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationConstraint_CompanyLocation_OnGroundInstallation`
    FOREIGN KEY (`idInstallation`)
    REFERENCES `urbanAgriDB`.`OnGroundInstallation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 14 Table `urbanAgriDB`.`CompanyLocation_OnRoofInstallation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (
  `idCompany` INT NOT NULL,
  `idInstallation` INT NOT NULL,
  `responsibleName` VARCHAR(500) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(20) NULL DEFAULT NULL,
  `employeesNumber` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `responsibleFirstName` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idCompany`, `idInstallation`),
  CONSTRAINT `idCompanyConstraint_CompanyLocation_OnRoofInstallation`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`Company` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationConstraint_CompanyLocation_OnRoofInstallation`
    FOREIGN KEY (`idInstallation`)
    REFERENCES `urbanAgriDB`.`OnRoofInstallation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 15 Table `urbanAgriDB`.`Objective_Business_OnRoof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Objective_Business_OnRoof` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Objective_Business_OnRoof` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idObjective` INT NOT NULL,
  `idBusiness` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idObjective`,`idBusiness`),
  CONSTRAINT `idCompanyConstraint_Objective_Business_OnRoof`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_Objective_Business_OnRoof`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idObjectiveConstraint_Objective_Business_OnRoof`
    FOREIGN KEY (`idObjective`)
    REFERENCES `urbanAgriDB`.`Objective` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idBusinessConstraint_Objective_Business_OnRoof`
    FOREIGN KEY (`idBusiness`)
    REFERENCES `urbanAgriDB`.`Business` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 16 Table `urbanAgriDB`.`Objective_Business_OnGround`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Objective_Business_OnGround` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Objective_Business_OnGround` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idObjective` INT NOT NULL,
  `idBusiness` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idObjective`,`idBusiness`),
  CONSTRAINT `idCompanyConstraint_Objective_Business_OnGround`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_Objective_Business_OnGround`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idObjectiveConstraint_Objective_Business_OnGround`
    FOREIGN KEY (`idObjective`)
    REFERENCES `urbanAgriDB`.`Objective` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idBusinessConstraint_Objective_Business_OnGround`
    FOREIGN KEY (`idBusiness`)
    REFERENCES `urbanAgriDB`.`Business` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 17 Table `urbanAgriDB`.`Business_InstallationType_OnGround`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Business_InstallationType_OnGround` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Business_InstallationType_OnGround` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idBusiness` INT NOT NULL,
  `idInstallationType` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`, `idBusiness`, `idInstallationType`),
  CONSTRAINT `idCompanyConstraint_Business_InstallationType_OnGround`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_Business_InstallationType_OnGround`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idBusinessConstraint_Business_InstallationType_OnGround`
    FOREIGN KEY (`idBusiness`)
    REFERENCES `urbanAgriDB`.`Business` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationTypeConstraint_Business_InstallationType_OnGround`
    FOREIGN KEY (`idInstallationType`)
    REFERENCES `urbanAgriDB`.`InstallationType` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- 18 Table `urbanAgriDB`.`Business_InstallationType_OnRoof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`Business_InstallationType_OnRoof` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`Business_InstallationType_OnRoof` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idBusiness` INT NOT NULL,
  `idInstallationType` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idBusiness`,`idInstallationType`),
  CONSTRAINT `idCompanyConstraint_Business_InstallationType_OnRoof`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_Business_InstallationType_OnRoof`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idBusinessConstraint_Business_InstallationType_OnRoof`
    FOREIGN KEY (idBusiness)
    REFERENCES `urbanAgriDB`.`Business` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationTypeConstraint_Business_InstallationType_OnRoof`
    FOREIGN KEY (idInstallationType)
    REFERENCES `urbanAgriDB`.`InstallationType` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 19 Table `urbanAgriDB`.`ProductionCriteria_OnGround`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`ProductionCriteria_OnGround` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`ProductionCriteria_OnGround` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idInstallationType` INT NOT NULL,
  `idFruitsAndVegetables` INT NOT NULL,
  `idIrrigationType` INT,
  `idFertilisationType` INT,
  `idPhytosanitaryFightType` INT,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idInstallationType`,`idFruitsAndVegetables`),
  CONSTRAINT `idCompanyConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationTypeConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (idInstallationType)
    REFERENCES `urbanAgriDB`.`InstallationType` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFruitsAndVegetablesConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (idFruitsAndVegetables)
    REFERENCES `urbanAgriDB`.`FruitsAndVegetablesProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idIrrigationTypeConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (idIrrigationType)
    REFERENCES `urbanAgriDB`.`IrrigationType` (`id`)
    ON UPDATE NO ACTION,
  CONSTRAINT `idFertilisationTypeConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (idFertilisationType)
    REFERENCES `urbanAgriDB`.`FertilisationType` (`id`)
    ON UPDATE NO ACTION,
  CONSTRAINT `idPhytosanitaryFightTypeConstraint_ProductionCriteria_OnGround`
    FOREIGN KEY (idPhytosanitaryFightType)
    REFERENCES `urbanAgriDB`.`PhytosanitaryFightType` (`id`)
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 20 Table `urbanAgriDB`.`ProductionCriteria_OnRoof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`ProductionCriteria_OnRoof` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`ProductionCriteria_OnRoof` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idInstallationType` INT NOT NULL,
  `idFruitsAndVegetables` INT NOT NULL,
  `idIrrigationType` INT NULL DEFAULT NULL,
  `idFertilisationType` INT NULL DEFAULT NULL,
  `idPhytosanitaryFightType` INT NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  CONSTRAINT `idCompanyConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idInstallationTypeConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idInstallationType`)
    REFERENCES `urbanAgriDB`.`InstallationType` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFruitsAndVegetablesConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idFruitsAndVegetables`)
    REFERENCES `urbanAgriDB`.`FruitsAndVegetablesProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idIrrigationTypeConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idIrrigationType`)
    REFERENCES `urbanAgriDB`.`IrrigationType` (`id`)
    ON UPDATE NO ACTION,
  CONSTRAINT `idFertilisationTypeConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idFertilisationType`)
    REFERENCES `urbanAgriDB`.`FertilisationType` (`id`)
    ON UPDATE NO ACTION,
  CONSTRAINT `idPhytosanitaryFightTypeConstraint_ProductionCriteria_OnRoof`
    FOREIGN KEY (`idPhytosanitaryFightType`)
    REFERENCES `urbanAgriDB`.`PhytosanitaryFightType` (`id`)
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 21 Table `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnRooof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnRoof` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnRoof` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idFruitsAndVegetables` INT NOT NULL,
  `idCommercialisationMode` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idFruitsAndVegetables`,`idCommercialisationMode`),
  CONSTRAINT `idCompanyConstraint_FAV_ComModeRoof`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_FAV_ComModeRoof`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFruitsAndVegetablesConstraint_FAV_ComModeRoof`
    FOREIGN KEY (idFruitsAndVegetables)
    REFERENCES `urbanAgriDB`.`FruitsAndVegetablesProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCommercialisationModeConstraint_FAV_ComModeRoof`
    FOREIGN KEY (idCommercialisationMode)
    REFERENCES `urbanAgriDB`.`CommercializationMode` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 22 Table `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnGround`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnGround` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FruitsAndVegetablesProducts_CommercialisationModeOnGround` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idFruitsAndVegetables` INT NOT NULL,
  `idCommercialisationMode` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idFruitsAndVegetables`,`idCommercialisationMode`),
  CONSTRAINT `idCompanyConstraint_FAV_ComModeGround`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_FAV_ComModeGround`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFruitsAndVegetablesConstraint_FAV_ComModeGround`
    FOREIGN KEY (idFruitsAndVegetables)
    REFERENCES `urbanAgriDB`.`FruitsAndVegetablesProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCommercialisationModeConstraint_FAV_ComModeGround`
    FOREIGN KEY (idCommercialisationMode)
    REFERENCES `urbanAgriDB`.`CommercializationMode` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 23 Table `urbanAgriDB`.`FarmingProducts_CommercialisationOnGround`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FarmingProducts_CommercialisationOnGround` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FarmingProducts_CommercialisationOnGround` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idCommercialisationMode` INT NOT NULL,
  `idFarmingProducts` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idCommercialisationMode`,`idFarmingProducts`),
  CONSTRAINT `idCompanyConstraint_FarmPdts_CommonOnGround`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_FarmPdts_CommonOnGround`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCommercialisationModeConstraint_FarmPdts_CommonOnGround`
    FOREIGN KEY (idCommercialisationMode)
    REFERENCES `urbanAgriDB`.`CommercializationMode` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFarmingProductsConstraint_FarmPdts_CommonOnGround`
    FOREIGN KEY (idFarmingProducts)
    REFERENCES `urbanAgriDB`.`FarmingProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 24 Table `urbanAgriDB`.`FarmingProducts_CommercialisationOnRoof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urbanAgriDB`.`FarmingProducts_CommercialisationOnRoof` ;

CREATE TABLE IF NOT EXISTS `urbanAgriDB`.`FarmingProducts_CommercialisationOnRoof` (
  `idCompany` INT NOT NULL,
  `idCompanyLocation` INT NOT NULL,
  `idCommercialisationMode` INT NOT NULL,
  `idFarmingProducts` INT NOT NULL,
  PRIMARY KEY (`idCompany`,`idCompanyLocation`,`idCommercialisationMode`,`idFarmingProducts`),
  CONSTRAINT `idCompanyConstraint_FarmPdts_CommonOnRoof`
    FOREIGN KEY (`idCompany`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idCompany`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompanyLocationConstraint_FarmPdts_CommonOnRoof`
    FOREIGN KEY (`idCompanyLocation`)
    REFERENCES `urbanAgriDB`.`CompanyLocation_OnRoofInstallation` (`idInstallation`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idCommercialisationModeConstraint_FarmPdts_CommonOnRoof`
    FOREIGN KEY (idCommercialisationMode)
    REFERENCES `urbanAgriDB`.`CommercializationMode` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idFarmingProductsConstraint_FarmPdts_CommonOnRoof`
    FOREIGN KEY (idFarmingProducts)
    REFERENCES `urbanAgriDB`.`FarmingProducts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- CREATION OF TESTS DATA
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`Company`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`Company` (`id`, `name`, `description`) VALUES (1, 'testNameCompany', 'testDescCompany');

COMMIT;


-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`OnGroundInstallation`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`OnGroundInstallation` (`id`, `country`, `address`, `zipCode`, `city`, `description`) VALUES (1, 'testCountryOnGroundLocation', 'testAdresssOngrondLocation', '13500', 'testCictyOnGroundLocation', 'testDescriptionOnGruondLocation');

COMMIT;


-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`Business`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`Business` (`id`, `name`, `description`) VALUES (1, 'testBusinessName', 'testBusinessDesc');

COMMIT;


-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`InstallationType`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`InstallationType` (`id`, `name`, `description`) VALUES (1, 'testNameInstalType', 'testDescInstType');

COMMIT;


-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`CompanyLocation_OnGroundInstallation`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`CompanyLocation_OnGroundInstallation` (`idCompany`, `idInstallation`, `responsibleName`, `phoneNumber`, `employeesNumber`, `description`, `responsibleFirstName`) VALUES (1, 1, 'testResponsibleNameCompOnG', '0485632175', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `urbanAgriDB`.`Business_InstallationType_OnGround`
-- -----------------------------------------------------
START TRANSACTION;
USE `urbanAgriDB`;
INSERT INTO `urbanAgriDB`.`Business_InstallationType_OnGround` (`idCompany`, `idCompanyLocation`, `idBusiness`, `idInstallationType`) VALUES (1, 1, 1, 1);

COMMIT;
